--- 
abstract: (DEPRECATED) File cache
author: Christian Hansen, C<ch@ngmedia.com>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Cache-FileCache
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::FileCache: 0
  Catalyst::Runtime: 5.7006
  Class::Data::Inheritable: 0
version: 0.7
